from character_new import *
from enemy_new import *
import colorama
colorama.init()

PRESENTATION = "\033[;31m" + "\n---------------Welcome to the beasts fight club!---------------\n" + '\033[0m'
ENEMY_LIST = ["Grom", "Thrum", "Doomhammer", "Skullsplitter", "Gorrum", "Nagrand", "Lok amon", "Grombolar", "Grommash", "Dae'mon","Grygnor", "Tromnantaus","Humnert","Urdaeun","Rhunnem","Hulnam","Ardan","Onzas","Aagrus","Zuzram"]
FIRST_MENU_OPTION = "\033[;33m" + "\nChoose the option you want to perform:\n 1: Choose character\n 2: Remove character:\n 3: Exit\n" + "\033[;0m"
YOUR_CHOICE = "\033[;35m" + "Your choice: " + "\033[;0m"
WRONG_CHOICE = "\033[;31m" + "\n----Your choice is incorrect!----" + "\033[;0m"
PRESS_TO_FIGHT = "\033[;32m" + "\nPress ENTER to fight\n" + "\033[;0m"
DAMAGE_CAUSED = "\033[;35m" +  f"Damage caused by: " + "\033[;0m"
HEALTH_POINTS = "\033[;35m" + "HP" + "\033[;0m"
IS_DEAD = "\033[;31m" + "is dead!" + "\033[;0m"
CURRENT_HEALTH =  "\033[;33m" + "Current health of " + "\033[;0m"
CONGRATS = "\033[;32m" + "Congratulations!" + "\033[;0m"
LEVEL_UP = "\033[;32m" + "has leveled up!" + "\033[;0m"
CURRENT_LEVEL = "Current level of: "
IS = "is"
CHAR_AMOUNT = "\033[;33m" + "How many characters do you want to add? (3 max): \n Your answer: " + "\033[;0m"
CHAR_AMOUNT_ERR = "\033[;31m" + "You can add up to 3 characters, 1 minimum!" + "\033[;0m"
CHOICE_TYPES_CHAR = "\033[;32m" + "\nEnter the type of character you want: \n 1:Orc: You'll get 2 extra points in strength\n 2:Elf: You'll get 2 extra points in agility\n 3:Human: You'll get 2 extra points in constitution\n" + "\033[;0m"
CHAR_CHOICE_ERROR = "\033[;31m" + "Your choice is not in the options!" + "\033[;0m"
CHAR_NAME = "\033[;35m" + "\nPlease, enter the character's name: \n Name: " + "\033[;0m"
CHAR_AGE = "\033[;35m" + "Please, enter character's age: \n Age: " + "\033[;0m"
SUM_ATTRIBS = "\033[;36m" + "\nThe sum of strength, agility and constitution must be 15, and no stat can be equal to 0" + "\033[;0m"
CHAR_STR = "\nEnter character's strength: "
YOU_HAVE = "\033[;32m" + "\nYou have" + "\033[;0m"
POINTS_LEFT = "\033[;32m" + "points left." + "\033[;0m"
CHAR_AGI = "\nEnter character's agility: "
CHAR_CONS = "\nEnter character's constitution: "
SUM_ERR = "\033[;31m" + "THE SUM OF THE STATS MUST BE 15, PLEASE ENTER THE VALUES AGAIN" + "\033[;0m"
NAME_OF_CHAR = "\033[;32m" + ": the name of this character is" + "\033[;0m"
RACE_IS = "\033[;32m" + "and it's race is" + "\033[;0m"
CHAR_TO_CHOOSE = "\nWhich character do you want to choose?\n Your Choice: "
SELECTED_CHAR = "\033[;32m" + "\nThe selected character is: " + "\033[;0m"
INVALID_SELECTION = "\033[;31m" + "Your selection is invalid or the character does not exist" + "\033[;0m"
CHAR_TO_REMOVE = "\nChoose the character you want to remove: "
CHAR_REMOVED = "\033[;31m" + "\nThe character was removed!" + "\033[;0m"
INVENTORY = "\n----------------INVENTORY:----------------\n"
POTION = ": , Potion:"
POTION_ADDED = "\033[;32m" + "A potion has been added to your inventory!" + "\033[;0m"
ARROW = "\033[;31m" + "----->" + "\033[;0m"
HAS_DROPPED = "\033[;32m" + "has dropped" + "\033[;0m"
POTION_SELECT = "\033[;32m" + "Select the POTION you want to use. Otherwise, press 0.\n Your choice: " + "\033[;0m"
NOW_FIGHTING = "\nYou're now fighting against"
YOU_WON = "\033[;32m" + "\nCongratulations! You have killed all of your Enemies!\n" + "\033[;0m"
GAME_OVER = "\033[;31m" + "\nThe game is OVER!\n" + "\033[;0m"